### ISSUE TITLE
Loose ends...

### ISSUE THREAD

**Issue by thierryk** [yahoo/acss-site#25]
@src-code @renatoi please add whatever you want to this list

- [x]  `D-ib` for oldIE?
- [x]  `IbBox` ("inline-block box") as a helper class mapped to `D-ib` + `Va-t` + oldIE fix for grid
- [x]  pseudo-class in atomic config i.e.: `.Td-n\:h:hover`
- [x]  contextual selector à la `active:h>Td-u` and `active:h_Td-u` 
- [ ]  concatenation/uglification of CSS files
- [x]  mobile first or desktop first? (IE7/8 do not do media queries)
- [x]  should we implement "auto-prefixer" so we can stay away from prefixes in the style sheets?
- [x]  should we include helpers with atomic?
- [x]  make sure that "shorthand" rules/declarations come before individual ones (i.e. `M-*` before `Mx-*` before `Mt-*`)
- [ ] submenu (mobile version) should close when user clicks outside of it or hit `escape` key

**Comment by src-code** [comment]
I vote mobile-first.

**Comment by thierryk** [comment]
But how do we deal with IE7/8 then? We would need to provide an extra style sheet for that, but then how do we serve it?

**Comment by src-code** [comment]
Append it to the main stylesheet.  Make old-IE support a configuration option, off by default?

**Comment by thierryk** [comment]
But the problem is that we do not have a mechanism that could generate that style sheet. It would be up to the end user to create a IE7/8 style sheet. In other words, we will be "promoting" dropping oldIE which is something I would really dislike doing.

**Comment by src-code** [comment]
Can't we create such a mechanism?  I'm not promoting the idea that end users have to create their own support - I just think we shouldn't burden anyone with IE7/8 if they don't need it (which is the vast majority of people who'll be using our stuff.)

**Comment by thierryk** [comment]
I think we can solve the issue if we modify the config to write media queries using `max-width` too, because this will allow users to design for *desktop first*, but then **overwrite** their styling for mobile.

For example:
```html
<div class="D-ib W-50% D-b--sm W-a--sm"></div>
```
In the case above, the MQ would be written like this:

```css
@media screen and (max-width: 600px) {
    .D-b--sm {
        display: block;
    }
    .W-a--sm {
        width: auto;
    }
}
```

Makes sense?

**Comment by thierryk** [comment]
Closing this in favor of new specific issues.
