### ISSUE TITLE
Malformed color strings should not create rules

### ISSUE THREAD

**Issue by thierryk** [yahoo/acss-site#65]
Today, the class `Bgc(#0280AE.5)` produces this style: `background-color: #028;`. 
But I think it should fail as it uses uppercase letters.

**Comment by src-code** [comment]
@thierryk I think you meant to open this issue against Atomizer, not the docs site?

But I'm curious, why not just support uppercase letters in hex values?  Is it to avoid duplicate rules?

**Comment by src-code** [comment]
Opened a new issue against Atomizer: https://github.com/yahoo/atomizer/issues/246
