### ISSUE TITLE
The markdown syntax for code is kinda broken

### ISSUE THREAD

**Issue by thierryk** [yahoo/acss-site#68]
In our pages, this gets properly formatted:
```css
#id .class {} /* comment */
```
but this does not:
```css
.class {} /* comment */
```

The problem is not related to `CSS` syntax though, I notice this issue with `html` too.

**Comment by renatoi** [comment]
@src-code Just want to give a shout-out for the awesome work on refactoring the docs. I ran it locally and it looks a lot better. However, this issue that Thierry reported is quite noticeable right in the landing page: the first example does not correctly apply the colors for the HTML. I believe this might be related to this: https://github.com/yahoo/acss-site/blob/master/app/services/docs.js#L20

The auto highlight might not be picking it up correctly. I believe there's a way to pass the correct language, be more explicit about which language it is being used.

**Comment by src-code** [comment]
@renatoi Actually I broke the examples, I think - I had gone in and removed the `$` prefix on some variables in our examples (I think they're confusing for developers) but didn't realize the examples were actually relying on the same style config as the site itself.  I'm about to push a fix for this!

**Comment by renatoi** [comment]
But this was broken even before any changes you recently did.

**Comment by src-code** [comment]
@renatoi Ah, you mean the code snippets?  As far as I can see, those snippets are styled manually with spans and classes, I don't think they're auto-styled?

**Comment by src-code** [comment]
@renatoi Updated master, check it out and see if it looks better!

**Comment by renatoi** [comment]
Looks really good. I guess this can be closed then.
